'use strict';

var WorldLevels = [
//level 1
{"buckets":[{"x":528,"y":878.5,"w":100,"h":50,"theta":0,"color":"blue","interactable":false,"hasBottom":true,"inColor":"red","outColor":"green"}],"influencers":[{"x":650,"y":110,"w":30,"h":30,"theta":0,"color":"blue","interactable":false,"radius":15,"force":5,"influenceRadius":75,"influenceType":1,"maxSizeFactor":3,"showInfluenceRing":true}],"obstacles":[],"portals":[],"sinks":[],"sources":[{"x":200,"y":100,"w":25,"h":25,"theta":0,"color":"red","interactable":false,"speed":2,"nparticles":50}],"stars":[],"gameGrid":{"w":768,"h":1024,"gridx":768,"gridy":1024,"lines":[{},{},{},{}]}},

//level 2
{"buckets":[{"x":374,"y":640.5,"w":100,"h":50,"theta":0,"color":"blue","interactable":false,"hasBottom":true,"inColor":"green","outColor":"green"},{"x":332,"y":412.5,"w":100,"h":50,"theta":0,"color":"blue","interactable":false,"hasBottom":false,"inColor":"red","outColor":"green"}],"influencers":[{"x":100,"y":912.5,"w":30,"h":30,"theta":0,"color":"blue","interactable":false,"radius":15,"force":5,"influenceRadius":75,"influenceType":1,"maxSizeFactor":3,"showInfluenceRing":true}],"obstacles":[],"portals":[],"sinks":[],"sources":[{"x":200,"y":100,"w":25,"h":25,"theta":0,"color":"red","interactable":false,"speed":2,"nparticles":50}],"stars":[],"gameGrid":{"w":768,"h":1024,"gridx":768,"gridy":1024,"lines":[{},{},{},{}]}},
    
//level3
{"buckets":[{"x":178,"y":854.5,"w":100,"h":50,"theta":0,"color":"blue","interactable":false,"hasBottom":true,"inColor":"green","outColor":"green"},{"x":332,"y":412.5,"w":100,"h":50,"theta":0,"color":"blue","interactable":false,"hasBottom":false,"inColor":"red","outColor":"green"}],"influencers":[{"x":478,"y":118.5,"w":30,"h":30,"theta":0,"color":"blue","interactable":false,"radius":15,"force":5,"influenceRadius":75,"influenceType":1,"maxSizeFactor":3,"showInfluenceRing":true},{"x":662,"y":116.5,"w":30,"h":30,"theta":0,"color":"blue","interactable":false,"radius":15,"force":5,"influenceRadius":75,"influenceType":1,"maxSizeFactor":3,"showInfluenceRing":true}],"obstacles":[],"portals":[],"sinks":[],"sources":[{"x":200,"y":100,"w":25,"h":25,"theta":0,"color":"red","interactable":false,"speed":2,"nparticles":50}],"stars":[],"gameGrid":{"w":2304,"h":3072,"gridx":768,"gridy":1024,"lines":[{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{}]}},

//level4
{"buckets":[{"x":656,"y":624,"w":100,"h":50,"theta":"180","color":"blue","interactable":false,"hasBottom":true,"inColor":"blue","outColor":"green"},{"x":332,"y":412.5,"w":100,"h":50,"theta":0,"color":"blue","interactable":false,"hasBottom":false,"inColor":"red","outColor":"green"}],"influencers":[{"x":430,"y":126,"w":30,"h":30,"theta":0,"color":"blue","interactable":false,"radius":15,"force":5,"influenceRadius":75,"influenceType":1,"maxSizeFactor":3,"showInfluenceRing":true},{"x":646,"y":130,"w":30,"h":30,"theta":0,"color":"blue","interactable":false,"radius":15,"force":5,"influenceRadius":75,"influenceType":1,"maxSizeFactor":3,"showInfluenceRing":true}],"obstacles":[],"portals":[],"sinks":[{"x":334,"y":604,"w":30,"h":30,"theta":0.844153986113171,"color":"green","interactable":false,"radius":15,"force":5,"isSource":true,"inColor":"green","outColor":"blue","influenceRadius":75,"influenceType":0,"maxSizeFactor":4,"targetSizeFactor":3,"influenceBound":false,"showInfluenceRing":true, "speed":9}],"sources":[{"x":200,"y":100,"w":25,"h":25,"theta":0,"color":"red","interactable":false,"speed":2,"nparticles":50}],"stars":[],"gameGrid":{"w":2304,"h":3072,"gridx":768,"gridy":1024,"lines":[{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{}]}},

//level 5
{"buckets":[{"x":396,"y":252,"w":200,"h":50,"theta":"270","color":"blue","interactable":false,"hasBottom":true,"inColor":"orange","outColor":"green"},{"x":622,"y":462,"w":100,"h":50,"theta":0,"color":"blue","interactable":false,"hasBottom":false,"inColor":"orange","outColor":"green"}],"influencers":[{"x":126,"y":252,"w":30,"h":30,"theta":0,"color":"blue","interactable":false,"radius":15,"force":"40","influenceRadius":75,"influenceType":1,"maxSizeFactor":3,"showInfluenceRing":true}],"obstacles":[],"portals":[],"sinks":[{"x":214,"y":482,"w":30,"h":30,"theta":-3.575174137541555,"color":"green","interactable":false,"radius":15,"force":5,"isSource":true,"inColor":"red","outColor":"blue","influenceRadius":75,"influenceType":0,"maxSizeFactor":4,"targetSizeFactor":1,"influenceBound":false,"showInfluenceRing":true},{"x":504,"y":794,"w":30,"h":30,"theta":-2.121345726578764,"color":"green","interactable":false,"radius":15,"force":"20","isSource":true,"inColor":"blue","outColor":"green","influenceRadius":75,"influenceType":0,"maxSizeFactor":4,"targetSizeFactor":1,"influenceBound":false,"showInfluenceRing":true, "speed":9}],"sources":[{"x":200,"y":100,"w":25,"h":25,"theta":0,"color":"red","interactable":false,"speed":6,"nparticles":50}],"stars":[],"gameGrid":{"w":2304,"h":3072,"gridx":768,"gridy":1024,"lines":[{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{}]}}
]
